export { FontAwesomeModule } from './fontawesome.module';
export { AnimationProp, FaProps } from './shared/models/props.model';
export { FaIconComponent } from './icon/icon.component';
export { FaDuotoneIconComponent } from './icon/duotone-icon.component';
export { FaConfig } from './config';
export { FaLayersComponent } from './layers/layers.component';
export { FaLayersTextComponent } from './layers/layers-text.component';
export { FaLayersCounterComponent } from './layers/layers-counter.component';
export { FaStackComponent } from './stack/stack.component';
export { FaStackItemSizeDirective } from './stack/stack-item-size.directive';
export { FaIconLibrary, FaIconLibraryInterface } from './icon-library';
