sudo: false
language: node_js
node_js: '12'
addons:
  chrome: stable
install:
  - yarn
script:
  - yarn format:enforce
  - yarn lint
  - yarn test
  - yarn test:schematics
  - yarn build
  - yarn build:schematics
  - yarn test:demo
  - yarn test:integration
