name: Check
on: pull_request
jobs:
  check5:
    name: Font Awesome 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn add -D @fortawesome/fontawesome-svg-core@1.2.36 @fortawesome/free-regular-svg-icons@5.15.4 @fortawesome/free-solid-svg-icons@5.15.4
      - run: yarn format:enforce
      - run: yarn lint
      - run: yarn test
      - run: yarn test:schematics
      - run: yarn build
      - run: yarn build:schematics
      - run: yarn test:demo
      - run: yarn webdriver-manager update --versions.chrome=`google-chrome --version | awk '{print $3}'` --standalone false --gecko false
      - run: yarn test:integration --configuration=ci
  check6:
    name: Font Awesome 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn format:enforce
      - run: yarn lint
      - run: yarn test
      - run: yarn test:schematics
      - run: yarn build
      - run: yarn build:schematics
      - run: yarn test:demo
      - run: yarn webdriver-manager update --versions.chrome=`google-chrome --version | awk '{print $3}'` --standalone false --gecko false
      - run: yarn test:integration --configuration=ci
